# Generated by Django 5.0.6 on 2024-07-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0009_deliverys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deliverys',
        ),
    ]
